<?

// Následující kód lze použít k registraci lokální verze vybrané skupiny polí. Místní skupina polí může poskytnout mnoho výhod, jako jsou rychlejší doby načítání, řízení verzí a dynamická pole / nastavení. Jednoduše zkopírujte a vložte následující kód do souboru functions.php svého motivu nebo jej vložte do externího souboru.

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_602522b20f859',
	'title' => 'Doporučení',
	'fields' => array(
		array(
			'key' => 'field_6025231005a5a',
			'label' => 'Text doporučení',
			'name' => 'text_doporuceni',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6025233005a5b',
			'label' => 'Jméno autora',
			'name' => 'jmeno_autora',
			'type' => 'text',
			'instructions' => 'Kdo Vás doporučuje? Např. "František Vosáhlo"',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6025235a05a5c',
			'label' => 'Popisek autora',
			'name' => 'popisek_autora',
			'type' => 'text',
			'instructions' => 'Např. "Ředitel Koblihárna.cz "',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_602523f4157a0',
			'label' => 'Foto autora',
			'name' => 'foto_autora',
			'type' => 'image',
			'instructions' => 'Fotografie autora (portrétní foto). Pokud nezadáte, zobrazí se výchozí obecný obrázek.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_60252470157a1',
			'label' => 'Oblíbené',
			'name' => 'oblibene',
			'type' => 'true_false',
			'instructions' => 'Označit jako oblíbené.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'doporuceni',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;